./PageRank1 pagerank_tests/10Kresults
./PageRank1 pagerank_tests/20Kresults
./PageRank1 pagerank_tests/30Kresults
./PageRank1 pagerank_tests/40Kresults
./PageRank1 pagerank_tests/50Kresults
./PageRank1 pagerank_tests/60Kresults
./PageRank1 pagerank_tests/70Kresults
./PageRank1 pagerank_tests/80Kresults
./PageRank1 pagerank_tests/90Kresults
./PageRank1 pagerank_tests/100Kresults
